AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - Gemfile*
    - bin/*
    - config/*.rb
    - config/**/*.rb
    - db/migrate/*.rb
    - lib/tasks/*.rake
    - node_modules/*
    - node_modules/**/*
    - Rakefile
    - spec/*.rb
    - spec/**/*.rb
    - test/*.rb
    - vendor/**/*
    - lib/solidus_subscriptions/testing_support/factories/**/*.rb
    - app/mailers/application_mailer.rb
    - solidus_subscriptions.gemspec
    - lib/generators/solidus_subscriptions/install/install_generator.rb
    - lib/solidus_subscriptions/config.rb
    - spec/dummy/**/**

Style/Alias:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylealias

Style/AsciiComments:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleasciicomments

Style/BeginBlock:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylebeginblock

Style/BlockDelimiters:
  Enabled: false
  EnforcedStyle: semantic
  StyleGuide: https://relaxed.ruby.style/#styleblockdelimiters

Style/CommentAnnotation:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylecommentannotation

Style/Documentation:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styledocumentation

Layout/DotPosition:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#layoutdotposition

Style/DoubleNegation:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styledoublenegation

Style/EndBlock:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleendblock

Style/FormatString:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleformatstring

Style/IfUnlessModifier:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleifunlessmodifier

Style/Lambda:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylelambda

Style/ModuleFunction:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylemodulefunction

Style/MultilineBlockChain:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylemultilineblockchain

Style/NegatedIf:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylenegatedif

Style/NegatedWhile:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylenegatedwhile

Style/ParallelAssignment:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleparallelassignment

Style/PercentLiteralDelimiters:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylepercentliteraldelimiters

Style/PerlBackrefs:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styleperlbackrefs

Style/Semicolon:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylesemicolon

Style/SignalException:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylesignalexception

Style/SingleLineBlockParams:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylesinglelineblockparams

Style/SingleLineMethods:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylesinglelinemethods

Layout/SpaceBeforeBlockBraces:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#layoutspacebeforeblockbraces

Layout/SpaceInsideParens:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#layoutspaceinsideparens

Style/SpecialGlobalVars:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylespecialglobalvars

Style/StringLiterals:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylestringliterals

Style/TrailingCommaInArguments:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#styletrailingcommainarguments

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
  StyleGuide: https://relaxed.ruby.style/#styletrailingcommainarrayliteral

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
  StyleGuide: https://relaxed.ruby.style/#styletrailingcommainhashliteral

Style/WhileUntilModifier:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylewhileuntilmodifier

Style/WordArray:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#stylewordarray

Lint/AmbiguousRegexpLiteral:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#lintambiguousregexpliteral

Lint/AssignmentInCondition:
  Enabled: false
  StyleGuide: https://relaxed.ruby.style/#lintassignmentincondition

Lint/UnusedMethodArgument:
  Exclude:
    - app/jobs/orders_canceled_job.rb
    - app/jobs/checkouts_create_job.rb
    - app/jobs/themes_publish_job.rb
    - app/jobs/orders_fulfilled_job.rb
    - app/jobs/checkouts_delete_job.rb
    - app/jobs/checkouts_update_job.rb
    - app/jobs/app_uninstalled_job.rb
    - app/jobs/customers_enable_job.rb
    - app/jobs/order_transactions_create_job.rb
    - app/jobs/orders_delete_job.rb
    - app/jobs/themes_update_job.rb
    - app/jobs/customers_create_job.rb
    - app/jobs/customers_delete_job.rb
    - app/jobs/orders_create_job.rb
    - app/jobs/customers_update_job.rb
    - app/jobs/orders_updated_job.rb
    - app/jobs/orders_partially_fulfilled_job.rb
    - app/jobs/customers_disable_job.rb
    - app/jobs/carts_update_job.rb
    - app/jobs/carts_create_job.rb
    - app/jobs/orders_paid_job.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false


# There are some cops that go beyond formatting, and fixing them
# may involve touching code in more involved ways. I want to enable
# and correct those individually, to ensure that we don't introduce
# bugs in our quest for clean code.

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - app/decorators/spree/controllers/api/line_items/create_subscription_line_items.rb
    - app/controllers/solidus_subscriptions/api/v1/line_items_controller.rb
    - app/controllers/solidus_subscriptions/api/v1/subscriptions_controller.rb

Style/AndOr:
  Exclude:
    - app/controllers/shopify_app/webhooks_controller.rb

Style/ColonMethodCall:
  Exclude:
    - app/controllers/shopify_app/sessions_controller.rb

Naming/MemoizedInstanceVariableName:
  Enabled: false